### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by 0x4f53** [0x4f53/Wristkey#18]
## To-do List

### Next update
- Fix slow load times on older devices (LG G Watch W100)
- Fix bug where items appear twice (duplicate entries during imports)
- Use single line JSONArray as value in EncryptedSharedPrefs file (as opposed to one entry per key)
- Add drag and reposition support (and save array repositioning to EncryptedSharedPrefs)
- Fix thread bug when app is sent into background
- Add HTTP server + PIN support to watch to receive from phone to watch (with QR code support for easy transfer, refer to #4 and #16)
- Add 3 categories in add menu (File import, Camera and Wireless), and add import services screen to next screen (preferably as a grid)
- Add cards with flippable card support. 

### Future
- Combine Student ID functionality and allow adding QR code and barcode passes (add support to scan images of passes/generate data from Google Wallet pass file). Save data by scanning barcode / qr code and combine with name of document

Sample data file:

```
{
    "2fa" : [
             "otpauth://<rest>",
             "otpauth://<rest>",
          ],
    "passes" : [
              {
                  "name" : "BlackHat",
                  "type" : "code128",
                  "data" : ""
              },
          ],
}
```

**Comment by gilcu3** [comment]
Hi, first, thank you for your work, this is currently my favourite OTP app in wear os (and unfortunately I use Wear OS 2 TicWatch Pro 3 Ultra). 
I think I fixed 2 and 5 in my fork. Feel free to take the changes from there. As I see you are doing a lot of changes, there is no point to make a pull request, as you should better know how to integrate them.

**Comment by 0x4f53** [comment]
Hey, thanks for the kind words. I've already made some of the fixes you've added on your fork, so you can sync your branches with mine if you'd like. Feel free to raise PRs if you add something cool.
