### ISSUE TITLE
[BUG] Force Close on start v3.0

### ISSUE THREAD

**Issue by gilcu3** [0x4f53/Wristkey#25]
App is force closing on start, both on 
Wear OS 3.5 (ticwatch pro 3 ultra) and Android 14(oneplus 7T, LineageOS)
Wristkey 3.0

**Comment by 0x4f53** [comment]
Can I have the logcat?

**Comment by gilcu3** [comment]
Sure! This was just taken on a fresh install on the phone.
[19_02-23-05-55_859.log](https://github.com/0x4f53/Wristkey/files/14337315/19_02-23-05-55_859.log)

**Comment by 0x4f53** [comment]
#32
