### ISSUE TITLE
It would be great if this app had a standalone client application that syncs with the watch.[FEATURE]

### ISSUE THREAD

**Issue by nelsonlobo99** [0x4f53/Wristkey#4]
After having used Wristkey for a while I think a standalone client app that syncs with the watch, and stores data on your phone in case you erase your match memory would be a cool addon.

**Comment by 4f77616973** [comment]
Yeah, I did think of this, but I can't seem to find the time these days. There are a few bugfixes I need to do too. But one day, definitely.

**Comment by 0x4f53** [comment]
#19
